# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180908_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cuenta_predial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
