# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180908_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nombre_predio',
            field=models.CharField(max_length=100),
        ),
    ]
