# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180910_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='metodo_pago',
            field=models.CharField(choices=[('PUE', 'Pago en una sola exhibici\xf3n'), ('PPD', 'Pago en parcialidades o diferido')], default='PUE', max_length=3),
        ),
    ]
