# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180927_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='forma_pago_rep',
            field=models.CharField(blank=True, choices=[('01', 'Efectivo'), ('02', 'Cheque nominativo'), ('03', 'Transferencia electr\xf3nica de fondos'), ('04', 'Tarjeta de cr\xe9dito'), ('05', 'Monedero electr\xf3nico'), ('06', 'Dinero electr\xf3nico'), ('08', 'Vales de despensa'), ('12', 'Daci\xf3n en pago'), ('13', 'Pago por subrogaci\xf3n'), ('14', 'Pago por consignaci\xf3n'), ('15', 'Condonaci\xf3n'), ('17', 'Compensaci\xf3n'), ('23', 'Novaci\xf3n'), ('24', 'Confusi\xf3n'), ('25', 'Remisi\xf3n de deuda'), ('26', 'Prescripci\xf3n o caducidad'), ('27', 'A satisfacci\xf3n del acreedor'), ('28', 'Tarjeta de d\xe9bito'), ('29', 'Tarjeta de servicios'), ('99', 'Por definir')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='num_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pdf_rep',
            field=models.FileField(null=True, upload_to='rep'),
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid_rep',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='xml_rep',
            field=models.FileField(null=True, upload_to='rep'),
        ),
    ]
